//alert(`hello,osamu!`)//
//alert(`hello,sugimoto!`)//
//alert(1+1);
//alert(Math.sqrt(1+1));
//alert(2+3);
//alert('2'+'3');
//alert(Number('2')+Number('3'));
//alert('2'+3);
//alert(Number('2')+3);
//alert(Math.sqrt(2+3));
//alert(1/0);
//alert(0/0);